In [1]:
# pip install numpy

In [7]:
import numpy as np

In [22]:
# 1D array

In [16]:
nums = [12,56,45,87,47]
arr_1d = np.array(nums)
arr_1d

array([12, 56, 45, 87, 47])

In [17]:
type(arr_1d)

numpy.ndarray

In [10]:
type(arr_1d[1])

numpy.int64

In [ ]:
# Access element

In [11]:
arr_1d[3]

87

In [18]:
arr_1d[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [19]:
arr_1d

array([12, 56, 45, 87, 47])

In [ ]:
# Array slicing

In [20]:
arr_1d[0:2]

array([12, 56])

In [30]:
arr_1d[-1]

47

In [40]:
# array shape

In [31]:
arr_1d.shape

(5,)

In [23]:
# 2d array

In [24]:
list_2d = [ [12,5,6] , [4,8,3] , [87,56,3] ]
arr_2d = np.array(list_2d)

In [25]:
arr_2d

array([[12,  5,  6],
       [ 4,  8,  3],
       [87, 56,  3]])

In [ ]:
# Access element

In [27]:
arr_2d[0,1]

5

In [29]:
arr_2d.shape

(3, 3)

In [41]:
arr_2d

array([[12,  5,  6],
       [ 4,  8,  3],
       [87, 56,  3]])

In [42]:
arr_2d[0,0:2]

array([12,  5])

In [32]:
# 3d array

In [33]:
list_3d = [ [ [23,45,56],[56,67,8] ] , [ [4,7,8], [3,8,7]] , [[34,7,8],[34,78,6]] ]

In [34]:
list_3d

[[[23, 45, 56], [56, 67, 8]],
 [[4, 7, 8], [3, 8, 7]],
 [[34, 7, 8], [34, 78, 6]]]

In [35]:
arr_3d = np.array(list_3d)

In [36]:
arr_3d

array([[[23, 45, 56],
        [56, 67,  8]],

       [[ 4,  7,  8],
        [ 3,  8,  7]],

       [[34,  7,  8],
        [34, 78,  6]]])

In [37]:
type(arr_3d)

numpy.ndarray

In [38]:
arr_3d.shape

(3, 2, 3)

In [39]:
arr_3d[0,1,0]

56

In [43]:
arr_3d

array([[[23, 45, 56],
        [56, 67,  8]],

       [[ 4,  7,  8],
        [ 3,  8,  7]],

       [[34,  7,  8],
        [34, 78,  6]]])

In [45]:
arr_3d[1,1,0:2]

array([3, 8])

In [46]:
arr_3d.shape

(3, 2, 3)

In [47]:
# 1D to 2D array

In [69]:
list_1d = [12,56,87,46,3,4]
arr_1d= np.array(list_1d)
arr_1d

array([12, 56, 87, 46,  3,  4])

In [70]:
arr_2d = arr_1d.reshape(3,2)

In [71]:
arr_2d

array([[12, 56],
       [87, 46],
       [ 3,  4]])

In [72]:
arr_2d.shape

(3, 2)

In [73]:
# 2d to 1d

In [78]:
arr_2d

array([[12, 56],
       [87, 46],
       [ 3,  4]])

In [83]:
arr_1 = arr_2d.reshape(-1)

In [84]:
arr_1.shape

(6,)

In [85]:
arr_1

array([12, 56, 87, 46,  3,  4])

In [86]:
#1d to 3d

In [87]:
list_2 = [1,2,3,4,5,6,7,8,9,10,11,12]

In [88]:
arr_1d = np.array(list_2)

In [89]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
arr_2 = arr_1d.reshape(3,2,2)

In [91]:
arr_2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [92]:
arr_2.shape

(3, 2, 2)

In [93]:
# 3d to 1d

In [94]:
arr_3 = arr_2.reshape(-1)

In [95]:
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
# 3d to 2d

In [97]:
arr_2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [98]:
arr_4 = arr_2.reshape(6,2)

In [99]:
arr_4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [100]:
# Iterating Arrays

In [101]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
for x in arr_1d:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [103]:
arr_2d

array([[12, 56],
       [87, 46],
       [ 3,  4]])

In [105]:
for x in arr_2d:
    for y in x:
        print(y)

12
56
87
46
3
4


In [106]:
arr_3d

array([[[23, 45, 56],
        [56, 67,  8]],

       [[ 4,  7,  8],
        [ 3,  8,  7]],

       [[34,  7,  8],
        [34, 78,  6]]])

In [110]:
for x in arr_3d:
    for y in x:
        for z in y:
            print(z)

23
45
56
56
67
8
4
7
8
3
8
7
34
7
8
34
78
6


In [111]:
for x in np.nditer(arr_3d):
    print(x)

23
45
56
56
67
8
4
7
8
3
8
7
34
7
8
34
78
6


In [112]:
# concating

In [113]:
arr_1 = np.array([23,67,5,7])
arr_2 = np.array([3,4,5,6])

In [114]:
arr_1

array([23, 67,  5,  7])

In [115]:
arr_2

array([3, 4, 5, 6])

In [116]:
arr_3 = np.concatenate([arr_1,arr_2])

In [117]:
arr_3

array([23, 67,  5,  7,  3,  4,  5,  6])

In [122]:
arr_4 = np.stack([arr_1,arr_2])
arr_4

array([[23, 67,  5,  7],
       [ 3,  4,  5,  6]])

In [123]:
arr_4 = np.stack([arr_1,arr_2],axis =1) # column wise
arr_4

array([[23,  3],
       [67,  4],
       [ 5,  5],
       [ 7,  6]])

In [124]:
arr_1

array([23, 67,  5,  7])

In [125]:
arr_2

array([3, 4, 5, 6])

In [126]:
arr_5 = np.hstack([arr_1,arr_2])
arr_5

array([23, 67,  5,  7,  3,  4,  5,  6])

In [127]:
arr_6 = np.vstack([arr_1,arr_2])
arr_6

array([[23, 67,  5,  7],
       [ 3,  4,  5,  6]])

In [128]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:
arr_1d.max()

12

In [130]:
arr_1d.min()

1

In [131]:
arr_1d.mean()

6.5