In [1]:
import numpy as np

In [2]:
arr_1d = np.array([10,20,30,40])
arr_1d

array([10, 20, 30, 40])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr_zeros = np.zeros((3,2))
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
arr_ones = np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr_eye = np.eye((3))
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
array_full = np.full((3,2),20)
array_full

array([[20, 20],
       [20, 20],
       [20, 20]])

In [19]:
np.random.randint(10,50)

33

In [20]:
np.random.randint(10,50,5)

array([23, 44, 12, 49, 44])

In [21]:
arr_2d = np.arange(1,10).reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr_2d = np.random.randint(1,10,9).reshape(3,3)
arr_2d

array([[1, 6, 6],
       [7, 4, 4],
       [8, 8, 7]])

### adding numpy arrays

In [26]:
n1 = np.array([10,20,30,40])
n2 = np.array([40,50,60,70])

In [27]:
np.sum([n1,n2])

320

In [28]:
np.sum([n1,n2], axis=0)

array([ 50,  70,  90, 110])

In [29]:
np.sum([n1,n2], axis=1)

array([100, 220])

### intersection and setdiff

In [30]:
n1

array([10, 20, 30, 40])

In [31]:
n2

array([40, 50, 60, 70])

In [32]:
np.intersect1d(n1,n2)

array([40])

In [33]:
np.setdiff1d(n2,n1) # n2 - n1

array([50, 60, 70])

In [35]:
np.setdiff1d(n1,n2) # n1- n2

array([10, 20, 30])

### Scaler operation

In [36]:
n1

array([10, 20, 30, 40])

In [37]:
n1 + 1

array([11, 21, 31, 41])

In [38]:
n1 - 5

array([ 5, 15, 25, 35])

In [39]:
n1 * 2

array([20, 40, 60, 80])

In [40]:
n1 /5

array([2., 4., 6., 8.])

### Math functions

In [41]:
np.mean(n1)

25.0

In [42]:
np.std(n1)

11.180339887498949

In [43]:
np.median(n1)

25.0

In [45]:
np.sort(n1)

array([10, 20, 30, 40])